version: '3.7'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root-password"
    volumes:
      - "./mysql/script:/docker-entrypoint-initdb.d"
      - "./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    ports:
      - 3308:3306

  redis:
    container_name: redis
    image: redis:alpine3.13
    volumes:
      - "./redis/data:/data"